version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci
      - run: npm run test

      - save_cache:
          paths:
            - $HOME/.npm
          key: npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}

  deploy:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - add_ssh_keys:
          fingerprints:
            - 08:55:09:f8:de:cc:e3:eb:3e:b3:74:31:58:39:26:83
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: git config --global user.email "robot@example.com"
      - run: git config --global user.name "CircleCI Robot"
      - run: npm ci
      - run:
          name: Deploy page
          command: npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
